name: DEV Client nuget release

on:
  push:
    tags: "dev-client-*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.101
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --no-build  --configuration Release

      - name: Replace to dev package id
        run: |
          sed -i -e 's%<PackageId>MyNoSqlServer.DataReader</PackageId>%<PackageId>MyNoSqlServer.DataReader.Dev</PackageId>%g' MyNoSqlServer.DataReader/MyNoSqlServer.DataReader.csproj
          sed -i -e 's%<PackageId>MyNoSqlServer20.DataReader</PackageId>%<PackageId>MyNoSqlServer20.DataReader.Dev</PackageId>%g' MyNoSqlServer20.DataReader/MyNoSqlServer20.DataReader.csproj
          sed -i -e 's%<PackageId>MyNoSqlServer.DataWriter</PackageId>%<PackageId>MyNoSqlServer.DataWriter.Dev</PackageId>%g' MyNoSqlServer.DataWriter/MyNoSqlServer.DataWriter.csproj
          sed -i -e 's%<PackageId>MyNoSqlServer20.DataWriter</PackageId>%<PackageId>MyNoSqlServer20.DataWriter.Dev</PackageId>%g' MyNoSqlServer20.DataWriter/MyNoSqlServer20.DataWriter.csproj

      - name: Create the package - Reader
        run: dotnet pack --configuration Release MyNoSqlServer.DataReader/MyNoSqlServer.DataReader.csproj /p:Version=${GITHUB_REF#refs/tags/dev-client-} 
      - name: Create the package - Reader20
        run: dotnet pack --configuration Release MyNoSqlServer20.DataReader/MyNoSqlServer20.DataReader.csproj /p:Version=${GITHUB_REF#refs/tags/dev-client-} 

      - name: Create the package - Writer
        run: dotnet pack --configuration Release MyNoSqlServer.DataWriter/MyNoSqlServer.DataWriter.csproj /p:Version=${GITHUB_REF#refs/tags/dev-client-} 
      - name: Create the package - Writer20
        run: dotnet pack --configuration Release MyNoSqlServer20.DataWriter/MyNoSqlServer20.DataWriter.csproj /p:Version=${GITHUB_REF#refs/tags/dev-client-} 

      - name: Publish the package to GPR - Reader
        run: dotnet nuget push MyNoSqlServer.DataReader/bin/Release/*.Dev.*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_TOCKEN }}
      - name: Publish the package to GPR - Reader20
        run: dotnet nuget push MyNoSqlServer20.DataReader/bin/Release/*.Dev.*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_TOCKEN }}

      - name: Publish the package to GPR - Writer
        run: dotnet nuget push MyNoSqlServer.DataWriter/bin/Release/*.Dev.*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_TOCKEN }}
      - name: Publish the package to GPR - Writer20
        run: dotnet nuget push MyNoSqlServer20.DataWriter/bin/Release/*.Dev.*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_TOCKEN }}



