name: DEV Client nuget release

on:
  push:
    tags: "dev-client-*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.101
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --no-build  --configuration Release

      - name: Create the package - Reader
        run: dotnet pack --configuration Release MyNoSqlServer.DataReader/MyNoSqlServer.DataReader.csproj /p:Version=${GITHUB_REF#refs/tags/dev-client-} /p:PackageId=MyNoSqlServer.DataReader.DEV
      - name: Create the package - Reader20
        run: dotnet pack --configuration Release MyNoSqlServer20.DataReader/MyNoSqlServer20.DataReader.csproj /p:Version=${GITHUB_REF#refs/tags/dev-client-} /p:PackageId=MyNoSqlServer.DataReader.DEV

      - name: Create the package - Writer
        run: dotnet pack --configuration Release MyNoSqlServer.DataWriter/MyNoSqlServer.DataWriter.csproj /p:Version=${GITHUB_REF#refs/tags/dev-client-} /p:PackageId=MyNoSqlServer.DataWriter.DEV
      - name: Create the package - Writer20
        run: dotnet pack --configuration Release MyNoSqlServer20.DataWriter/MyNoSqlServer20.DataWriter.csproj /p:Version=${GITHUB_REF#refs/tags/dev-client-} /p:PackageId=MyNoSqlServer.DataWriter.DEV


