name: Release Server
on:
  push:
    tags: "Server-*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release 

    - name: Publish Server
      run: dotnet publish --no-build ./MyNoSqlServer.Api/MyNoSqlServer.Api.csproj --output ./publish-api --configuration Release /p:AssemblyVersion=${GITHUB_REF#refs/tags/Server-}

      
    - name: Publish Server to Registry
      uses: swisschain/Publish-Docker-Github-Action@master
      with:
        name: swisschains/MyNoSqlServerApi
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ./publish-api
        # snapshot: true # use snapshot to push an additional image, which is tagged with {YEAR}{MONTH}{DAY}{HOUR}{MINUTE}{SECOND}{first 6 digits of the git sha}
        tag_names: true  
        tag_name_skip: Server- 
